[repository]
name = "hyprwinsnap"
authors = ["quy"]

[hyprwinsnap]
description = "Snap floating window sizes to configurable presets while resizing"
authors = ["quy"]
output = "build/hyprwinsnap.so"
build = [
    "meson setup build --buildtype=release --prefix=/usr",
    "ninja -C build",
]